# fly.toml app configuration file generated for nutriplan-rails on 2025-04-06T10:18:03-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nutriplan-rails'
primary_region = 'gig'
console_command = '/rails/bin/rails console'

[build]
  [build.args]
    BUNDLER_VERSION = "2.6.7"
    NODE_VERSION = "18.15.0"
    RUBY_VERSION = "3.2.2"

[deploy]
  release_command = './bin/rails db:prepare'

[env]
  PORT = '8080'
  RAILS_ENV = "production"
  RACK_ENV = "production"
  RAILS_SERVE_STATIC_FILES = "true"
  RAILS_LOG_TO_STDOUT = "true"

[processes]
  app = './bin/rails server'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
